name: app_receitas
description: A new Flutter project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  google_fonts: ^5.1.0
  flutter_svg: ^2.0.7
  sembast: ^3.5.0+1
  uuid: ^3.0.7
  path: ^1.8.3
  path_provider: ^2.0.15
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  google_sign_in: ^6.1.5
  get_it: ^7.6.2
  flutter_native_splash: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  image: "assets/images/logo.png"
  android: true
  color: "#FFFFFF"
  android_12:
    image: "assets/images/logo.png"
    icon_background_color: "#101636"